version: 1.10.0.{build}

image: Visual Studio 2019

install:
  - pwsh: Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
  - pwsh: ./dotnet-install.ps1  -Channel 6.0.1xx -Quality preview
  #- ps: ./dotnet-install.ps1 -JsonFile global.json

init:
- git config --global core.autocrlf true

environment:
  DOTNET_VERSION: "6.0.100-rc.2.21505.57"

build_script:
- ps: dotnet pack -c Release -o artifacts

test_script:
- ps: dotnet test

artifacts:
- path: artifacts\*.nupkg
